name: Deploy Laravel Jobber App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.APP_DIR }}
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader

            # ✅ Install Node dependencies and build assets
            npm ci
            npm run build

            # Fix permissions for Laravel
            chown -R www-data:www-data storage bootstrap/cache database
            chmod -R 775 storage bootstrap/cache
            chmod 664 database/database.sqlite

            # Run migrations and clear caches
            php artisan migrate --force
            php artisan config:clear
            php artisan config:cache
            php artisan route:clear
            php artisan route:cache
            php artisan view:clear
            php artisan view:cache
          EOF
